### ISSUE TITLE
Problem running the code

### ISSUE THREAD

**Issue by jechenn** [Qingbao/iris#3]
Hi, im very new to matlab and i have some problem running the code, is it possible to ask for some guidance to run them? thank you

**Comment by Qingbao** [comment]
Please describe your issue with details.

**Comment by jechenn** [comment]
Is it possible to have some sort of video meeting to share my screen so I can show? since I don't really know anything much about matlab.. Thank you

**Comment by Qingbao** [comment]
Then learn it.
